import dayjs from 'dayjs';
import { Product, ProductCategory, StockStatus } from '../../../Utils/Types';
import { createSlice } from '@reduxjs/toolkit';

interface IinitialState {
  inventoryProducts: Product[];
}

const initialState = {
  inventoryProducts: [
    {
      productId: '92de2fec',
      name: 'Marcs Engine Oil',
      category: ProductCategory.AUTOMOTIVE_AND_CAR_CARE,
      productCode: '1a4ba7f1',
      quantityInStock: 20,
      minQuantity: 5,
      unitPrice: 140,
      dateOfArrival: dayjs(new Date()),
      supplierId: '68b599a1',
      shelfLifeDuration: '5 years',
      stockStatus: StockStatus.IN_STOCK,
    },
    {
      productId: '34fde790',
      name: 'Super Clean Glass Cleaner',
      category: ProductCategory.AUTOMOTIVE_AND_CAR_CARE,
      productCode: 'f8121d76',
      quantityInStock: 2,
      minQuantity: 3,
      unitPrice: 75,
      dateOfArrival: new Date(),
      supplierId: 'a2b4e5c6',
      shelfLifeDuration: '2 years',
      stockStatus: StockStatus.LOW_IN_STOCK,
    },
    {
      productId: 'c7b2e183',
      name: 'Ultra Shine Car Wax',
      category: ProductCategory.AUTOMOTIVE_AND_CAR_CARE,
      productCode: '6892f743',
      quantityInStock: 0,
      minQuantity: 2,
      unitPrice: 200,
      dateOfArrival: new Date(),
      supplierId: 'd3f1a8b5',
      shelfLifeDuration: '3 years',
      stockStatus: StockStatus.OUT_OF_STOCK,
    },
    {
      product_id: '6b93903e',
      name: 'Fresh Apples',
      category: ProductCategory.FRESH_PRODUCE,
      product_code: '6c8b3eaf',
      quantity_in_stock: 50,
      min_quantity: 10,
      unit_price: 3,
      date_of_arrival: new Date(),
      supplier_id: 'e54a1f9c',
      shelf_life_duration: '2 weeks',
      stock_status: StockStatus.IN_STOCK,
    },
    {
      product_id: '1dfcf9e7',
      name: 'Cheddar Cheese',
      category: ProductCategory.DAIRY_AND_EGGS,
      product_code: '8b327a13',
      quantity_in_stock: 8,
      min_quantity: 15,
      unit_price: 10,
      date_of_arrival: new Date(),
      supplier_id: '24f6dc8b',
      shelf_life_duration: '1 month',
      stock_status: StockStatus.LOW_IN_STOCK,
    },
    {
      product_id: 'd2e015ab',
      name: 'Ground Beef',
      category: ProductCategory.MEAT_AND_POULTRY,
      product_code: '3f7e9014',
      quantity_in_stock: 5,
      min_quantity: 10,
      unit_price: 12,
      date_of_arrival: new Date(),
      supplier_id: '7cbe0a96',
      shelf_life_duration: '3 days',
      stock_status: StockStatus.LOW_IN_STOCK,
    },
    {
      product_id: '84d97524',
      name: 'Frozen Shrimp',
      category: ProductCategory.FROZEN_FOODS,
      product_code: 'bcf8d1e0',
      quantity_in_stock: 18,
      min_quantity: 5,
      unit_price: 15,
      date_of_arrival: new Date(),
      supplier_id: '5c42fb6a',
      shelf_life_duration: '6 months',
      stock_status: StockStatus.IN_STOCK,
    },
    {
      product_id: 'f2a865d5',
      name: 'Toilet Paper',
      category: ProductCategory.HOUSEHOLD_SUPPLIES,
      product_code: '9d8b1c3d',
      quantity_in_stock: 4,
      min_quantity: 6,
      unit_price: 8,
      date_of_arrival: new Date(),
      supplier_id: 'f8d3e1a9',
      shelf_life_duration: 'N/A',
      stock_status: StockStatus.LOW_IN_STOCK,
    },
    {
      product_id: '723cfae2',
      name: 'Chocolate Bar',
      category: ProductCategory.CANDY_AND_SWEETS,
      product_code: '2e6d8c1b',
      quantity_in_stock: 12,
      min_quantity: 10,
      unit_price: 2,
      date_of_arrival: new Date(),
      supplier_id: 'a0b4f2d3',
      shelf_life_duration: '1 year',
      stock_status: StockStatus.IN_STOCK,
    },
    {
      product_id: 'a395df62',
      name: 'Hand Soap',
      category: ProductCategory.PERSONAL_CARE_AND_HYGIENE,
      product_code: 'f5c8a3d4',
      quantity_in_stock: 3,
      min_quantity: 5,
      unit_price: 5,
      date_of_arrival: new Date(),
      supplier_id: '3e07b28c',
      shelf_life_duration: 'N/A',
      stock_status: StockStatus.LOW_IN_STOCK,
    },
    {
      product_id: 'e3d627f9',
      name: 'Paper Towels',
      category: ProductCategory.HOUSEHOLD_SUPPLIES,
      product_code: 'c2a1b6d7',
      quantity_in_stock: 2,
      min_quantity: 4,
      unit_price: 6,
      date_of_arrival: new Date(),
      supplier_id: '8e9f4b0a',
      shelf_life_duration: 'N/A',
      stock_status: StockStatus.LOW_IN_STOCK,
    },
    {
      product_id: '3c097ba6',
      name: 'Chicken Noodle Soup',
      category: ProductCategory.CANNED_AND_PACKAGED_GOODS,
      product_code: '5a6b4c3d',
      quantity_in_stock: 10,
      min_quantity: 15,
      unit_price: 4,
      date_of_arrival: new Date(),
      supplier_id: 'f0e8d6c4',
      shelf_life_duration: '2 years',
      stock_status: StockStatus.LOW_IN_STOCK,
    },
    {
      product_id: '3a6b9c2d',
      name: 'Granola Bars',
      category: ProductCategory.SNACKS_AND_CHIPS,
      product_code: '7d8e9f1a',
      quantity_in_stock: 45,
      min_quantity: 30,
      unit_price: 3,
      date_of_arrival: new Date(),
      supplier_id: 'b0c4d8e2',
      shelf_life_duration: '6 months',
      stock_status: StockStatus.IN_STOCK,
    },
    {
      product_id: '87f6c3d1',
      name: 'Orange Juice',
      category: ProductCategory.BEVERAGES,
      product_code: '2a9b8c7d',
      quantity_in_stock: 0,
      min_quantity: 5,
      unit_price: 4,
      date_of_arrival: new Date(),
      supplier_id: '4e5f6a7b',
      shelf_life_duration: '1 week',
      stock_status: StockStatus.OUT_OF_STOCK,
    },
    {
      product_id: 'b9e8d7c6',
      name: 'Yogurt',
      category: ProductCategory.DAIRY_AND_EGGS,
      product_code: '3a2b1c9d',
      quantity_in_stock: 20,
      min_quantity: 10,
      unit_price: 2,
      date_of_arrival: new Date(),
      supplier_id: 'f0e1d2c3',
      shelf_life_duration: '1 month',
      stock_status: StockStatus.IN_STOCK,
    },
    {
      product_id: '1a2b3c4d',
      name: 'Pasta Sauce',
      category: ProductCategory.CANNED_AND_PACKAGED_GOODS,
      product_code: '5e6f7a8b',
      quantity_in_stock: 30,
      min_quantity: 20,
      unit_price: 3,
      date_of_arrival: new Date(),
      supplier_id: 'd4c3b2a1',
      shelf_life_duration: '2 years',
      stock_status: StockStatus.IN_STOCK,
    },
    {
      product_id: '9a8b7c6d',
      name: 'Toothpaste',
      category: ProductCategory.PERSONAL_CARE_AND_HYGIENE,
      product_code: '4d3c2b1a',
      quantity_in_stock: 16,
      min_quantity: 10,
      unit_price: 3,
      date_of_arrival: new Date(),
      supplier_id: 'e1f2g3h4',
      shelf_life_duration: 'N/A',
      stock_status: StockStatus.IN_STOCK,
    },
  ],
};

export const inventorySlice = createSlice({
  name: 'inventory',
  initialState,
  reducers: {},
  extraReducers: (builder) => {},
});

export default inventorySlice.reducer;
