import dayjs from 'dayjs';
import { ProductCategory, StockStatus } from '../../../Utils/Types';

const inventoryProductSeed = [
  {
    product_id: '92de2fec',
    name: 'Marcs Engine Oil',
    category: ProductCategory.AUTOMOTIVE_AND_CAR_CARE,
    product_code: '1a4ba7f1',
    quantity_in_stock: 20,
    min_quantity: 5,
    unit_price: 140,
    date_of_arrival: dayjs(new Date()),
    expiry_date: dayjs(new Date()),
    supplier_id: '68b599a1',
    quantity: 23,
    unit_of_measurement: 'Carton',
    shelf_life_duration: '5 years',
    quantity_sold: 23,
    stock_status: StockStatus.IN_STOCK,
  },
  {
    product_id: '34fde790',
    name: 'Super Clean Glass Cleaner',
    category: ProductCategory.AUTOMOTIVE_AND_CAR_CARE,
    product_code: 'f8121d76',
    quantity_in_stock: 2,
    min_quantity: 3,
    unit_price: 75,
    date_of_arrival: new Date(),
    supplier_id: 'a2b4e5c6',
    shelf_life_duration: '2 years',
    stock_status: StockStatus.LOW_IN_STOCK,
    quantity_sold: 53,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: 'c7b2e183',
    name: 'Ultra Shine Car Wax',
    category: ProductCategory.AUTOMOTIVE_AND_CAR_CARE,
    product_code: '6892f743',
    quantity_in_stock: 0,
    min_quantity: 2,
    unit_price: 200,
    date_of_arrival: new Date(),
    supplier_id: 'd3f1a8b5',
    shelf_life_duration: '3 years',
    quantity_sold: 744,
    stock_status: StockStatus.OUT_OF_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: '6b93903e',
    name: 'Fresh Apples',
    category: ProductCategory.FRESH_PRODUCE,
    product_code: '6c8b3eaf',
    quantity_in_stock: 50,
    min_quantity: 10,
    unit_price: 3,
    date_of_arrival: new Date(),
    supplier_id: 'e54a1f9c',
    shelf_life_duration: '2 weeks',
    stock_status: StockStatus.IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity_sold: 233,
    quantity: 12,
    unit_of_measurement: 'Piece',
  },
  {
    product_id: '1dfcf9e7',
    name: 'Cheddar Cheese',
    category: ProductCategory.DAIRY_AND_EGGS,
    product_code: '8b327a13',
    quantity_in_stock: 8,
    min_quantity: 15,
    unit_price: 10,
    date_of_arrival: new Date(),
    supplier_id: '24f6dc8b',
    shelf_life_duration: '1 month',
    quantity_sold: 233,
    stock_status: StockStatus.LOW_IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 63,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: 'd2e015ab',
    name: 'Ground Beef',
    category: ProductCategory.MEAT_AND_POULTRY,
    product_code: '3f7e9014',
    quantity_in_stock: 5,
    min_quantity: 10,
    unit_price: 12,
    date_of_arrival: new Date(),
    supplier_id: '7cbe0a96',
    shelf_life_duration: '3 days',
    quantity_sold: 233,
    stock_status: StockStatus.LOW_IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 12,
    unit_of_measurement: 'Kilogram',
  },
  {
    product_id: '84d97524',
    name: 'Frozen Shrimp',
    category: ProductCategory.FROZEN_FOODS,
    product_code: 'bcf8d1e0',
    quantity_in_stock: 18,
    min_quantity: 5,
    unit_price: 15,
    date_of_arrival: new Date(),
    supplier_id: '5c42fb6a',
    shelf_life_duration: '6 months',
    quantity_sold: 233,
    stock_status: StockStatus.IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 14,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: 'f2a865d5',
    name: 'Toilet Paper',
    category: ProductCategory.HOUSEHOLD_SUPPLIES,
    product_code: '9d8b1c3d',
    quantity_in_stock: 4,
    min_quantity: 6,
    unit_price: 8,
    quantity_sold: 233,
    date_of_arrival: new Date(),
    supplier_id: 'f8d3e1a9',
    shelf_life_duration: 'N/A',
    stock_status: StockStatus.LOW_IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 10,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: '723cfae2',
    name: 'Chocolate Bar',
    category: ProductCategory.CANDY_AND_SWEETS,
    product_code: '2e6d8c1b',
    quantity_in_stock: 12,
    min_quantity: 10,
    unit_price: 2,
    date_of_arrival: new Date(),
    supplier_id: 'a0b4f2d3',
    shelf_life_duration: '1 year',
    quantity_sold: 233,
    stock_status: StockStatus.IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: 'a395df62',
    name: 'Hand Soap',
    category: ProductCategory.PERSONAL_CARE_AND_HYGIENE,
    product_code: 'f5c8a3d4',
    quantity_in_stock: 3,
    min_quantity: 5,
    unit_price: 5,
    date_of_arrival: new Date(),
    supplier_id: '3e07b28c',
    shelf_life_duration: 'N/A',
    stock_status: StockStatus.LOW_IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity_sold: 233,
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: 'e3d627f9',
    name: 'Paper Towels',
    category: ProductCategory.HOUSEHOLD_SUPPLIES,
    product_code: 'c2a1b6d7',
    quantity_in_stock: 2,
    min_quantity: 4,
    unit_price: 6,
    quantity_sold: 233,
    date_of_arrival: new Date(),
    supplier_id: '8e9f4b0a',
    shelf_life_duration: 'N/A',
    stock_status: StockStatus.LOW_IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: '3c097ba6',
    name: 'Chicken Noodle Soup',
    category: ProductCategory.CANNED_AND_PACKAGED_GOODS,
    product_code: '5a6b4c3d',
    quantity_in_stock: 10,
    min_quantity: 15,
    unit_price: 4,
    date_of_arrival: new Date(),
    supplier_id: 'f0e8d6c4',
    shelf_life_duration: '2 years',
    quantity_sold: 233,
    stock_status: StockStatus.LOW_IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: '3a6b9c2d',
    name: 'Granola Bars',
    category: ProductCategory.SNACKS_AND_CHIPS,
    product_code: '7d8e9f1a',
    quantity_in_stock: 45,
    min_quantity: 30,
    unit_price: 3,
    quantity_sold: 233,
    date_of_arrival: new Date(),
    supplier_id: 'b0c4d8e2',
    shelf_life_duration: '6 months',
    stock_status: StockStatus.IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: '87f6c3d1',
    name: 'Orange Juice',
    category: ProductCategory.BEVERAGES,
    quantity_sold: 233,
    product_code: '2a9b8c7d',
    quantity_in_stock: 0,
    min_quantity: 5,
    unit_price: 4,
    date_of_arrival: new Date(),
    supplier_id: '4e5f6a7b',
    shelf_life_duration: '1 week',
    stock_status: StockStatus.OUT_OF_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    category: ProductCategory.CLOTHING_AND_ACCESSORIES,
    date_of_arrival: dayjs('2023-02-22'),
    expiry_date: dayjs('2023-12-10'),
    name: 'Cotton T-Shirt',
    product_code: '01d97e2c',
    product_id: '5e66d1890ba5',
    quantity: 12,
    quantity_in_stock: 3,
    shelf_life_duration: '1 Year',
    supplier_id: '1a240',
    unit_of_measurement: 'Pieces',
    unit_price: 4500,
    quantity_sold: 233,
    min_quantity: 10,
    stock_status: StockStatus.LOW_IN_STOCK,
  },
  {
    category: ProductCategory.GROCERIES,
    date_of_arrival: dayjs('2023-03-15'),
    expiry_date: dayjs('2024-01-05'),
    name: 'Rice',
    product_code: '8f37e0a9',
    product_id: '1b41c5d7',
    quantity: 25,
    quantity_in_stock: 20,
    shelf_life_duration: '2 Years',
    supplier_id: '3f59b41c',
    unit_of_measurement: 'Kilograms',
    quantity_sold: 123,
    unit_price: 2500,
    min_quantity: 30,
    stock_status: StockStatus.IN_STOCK,
  },
  {
    category: ProductCategory.MEAT_AND_POULTRY,
    date_of_arrival: dayjs('2023-04-02'),
    expiry_date: dayjs('2023-07-31'),
    name: 'Chicken Breast',
    product_code: 'f32a85e6',
    product_id: '9c39e4a2',
    quantity: 10,
    quantity_in_stock: 0,
    shelf_life_duration: '3 Days',
    supplier_id: '7d53e109',
    unit_of_measurement: 'Pounds',
    unit_price: 3500,
    min_quantity: 5,
    quantity_sold: 343,
    stock_status: StockStatus.OUT_OF_STOCK,
  },
  {
    product_id: 'b9e8d7c6',
    name: 'Yogurt',
    category: ProductCategory.DAIRY_AND_EGGS,
    product_code: '3a2b1c9d',
    quantity_in_stock: 20,
    min_quantity: 10,
    unit_price: 2,
    quantity_sold: 233,
    date_of_arrival: new Date(),
    supplier_id: 'f0e1d2c3',
    shelf_life_duration: '1 month',
    stock_status: StockStatus.IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: '1a2b3c4d',
    name: 'Pasta Sauce',
    category: ProductCategory.CANNED_AND_PACKAGED_GOODS,
    product_code: '5e6f7a8b',
    quantity_in_stock: 30,
    min_quantity: 20,
    unit_price: 3,
    quantity_sold: 233,
    date_of_arrival: new Date(),
    supplier_id: 'd4c3b2a1',
    shelf_life_duration: '2 years',
    stock_status: StockStatus.IN_STOCK,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
  {
    product_id: '9a8b7c6d',
    name: 'Toothpaste',
    category: ProductCategory.PERSONAL_CARE_AND_HYGIENE,
    product_code: '4d3c2b1a',
    quantity_in_stock: 16,
    min_quantity: 10,
    unit_price: 3,
    date_of_arrival: new Date(),
    supplier_id: 'e1f2g3h4',
    shelf_life_duration: 'N/A',
    stock_status: StockStatus.IN_STOCK,
    quantity_sold: 233,
    expiry_date: dayjs(new Date()),
    quantity: 32,
    unit_of_measurement: 'Pack',
  },
];

export default inventoryProductSeed;
